version: '3.8'

networks:
  builder:
    name: builder
    external: false

services:
  database:
    image: postgres:14.2
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: p@$$vv0rD
      POSTGRES_DB: builder
    networks:
      - builder

  app:
    build:

      context: .
      dockerfile: Dockerfile
      args:
        STAGE: ${STAGE}
        NEXT_PUBLIC_LICENSE_CONSENT: ${NEXT_PUBLIC_LICENSE_CONSENT}
        NEXT_PUBLIC_WEBAPP_URL: ${NEXT_PUBLIC_WEBAPP_URL}
        NEXT_PUBLIC_APP_URL: ${NEXT_PUBLIC_APP_URL}
        DATABASE_URL: postgresql://postgres:p@$$vv0rD@database:5432/builder
        NEXTAUTH_SECRET: ${NEXTAUTH_SECRET}
        CALENDSO_ENCRYPTION_KEY: ${CALENDSO_ENCRYPTION_KEY}
        CALCOM_TELEMETRY_DISABLE: ${CALCOM_TELEMETRY_DISABLED}
      network: builder
