name: Build docker image and push to ghcr.io

on:
  push:
    branches:
      - production
    paths:
      - 'docker/**'
  workflow_dispatch:

env:
  AWS_REGION: us-east-2
  APP: calendso
  STAGE: ${{ github.ref_name }}
  SHA: ${{ github.sha }}

jobs:
  build:
    name: Build and push
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: 'true'
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}
          mask-aws-account-id: false
      - name: Login to GHCR
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 1.2.4
          terraform_wrapper: false
      - name: Terraform init
        id: init
        run: terraform init -no-color
      - name: Select terraform workspace
        id: select-workspace
        run: terraform workspace select ${{ env.STAGE }}
      - name: Terraform output
        id: output
        run: |
          terraform output -json -no-color > output.json
          cat output.json
      - name: Prepare build args list
        id: build-args
        run: |
          jq ".app_image_build_args.value" -Mr output.json | jq 'keys[] as $k | "\($k)=\(.[$k])"' -Mr > build_args.env
          echo ::set-output name=build_args::$(cat build_args.env)
      - name: Build and push docker image
        uses: docker/build-push-action@v3
        with:
          context: docker/.
          build-args: ${{ steps.output.puts.build_args }}
          tags: |
            ghcr.io/norumin/calendso:${{ env.SHA }}
            ghcr.io/norumin/calendso:${{ env.STAGE }}
            ghcr.io/norumin/calendso:latest
          push: true
